app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings

from book.views import LoginUserView, RecipeCreate, RecipeDetail, RecipeList, RegistrationView  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RecipeList.as_view(), name='recipes'),
    path('recipe_create/', login_required(RecipeCreate.as_view()), name='recipe_create'),
    path('recipe/<int:pk>/', RecipeDetail.as_view(), name='recipe'),
    path('accounts/login/', LoginUserView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('author/<int:id_author>/', RecipeList.as_view(), name='author'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Author(AbstractUser):
    email = models.EmailField(max_length=128, unique=True)

    class Meta:
        app_label = "book"
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"

    def __str__(self):
        return self.username


class Ingredient(models.Model):
    title = models.CharField(
        "Название", max_length=255, db_index=True
    )

    class Meta:
        app_label = "book"
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"

    def __str__(self):
        return self.title


class Recipe(models.Model):
    title = models.CharField(
        "Название", max_length=255, db_index=True
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="Автор", related_name="recipe", on_delete=models.PROTECT
    )

    img_recipe = models.ImageField(upload_to='img_recipe')

    description = models.CharField("Описание", max_length=255, blank=True)
    text_recipe = models.TextField("Текст рецепта", blank=True)
    created_at = models.DateTimeField("Время создания записи", auto_now_add=True)
    updated_at = models.DateTimeField("Время обновления записи", auto_now=True)

    class Meta:
        app_label = "book"
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="recipe_ingredient")
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name="ingredient")
    quantity = models.FloatField()
    UNITY_CHOICES = (
        ('g', 'gram'),
        ('ml', 'millilitre')

    )
    unity = models.CharField(max_length=2, choices=UNITY_CHOICES, default='g')

    class Meta:
        app_label = "book"
        verbose_name = "Ингредиент рецепта"
        verbose_name_plural = "Ингредиенты рецептов"

    def __str__(self):
        return f'{self.recipe}, {self.ingredient}, {self.quantity}, {self.unity}'
    

book/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import Author, RecipeIngredient, Recipe


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               }
    ))

    class Meta:
        model = Author
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', }))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ('username', 'email', 'password1',)


class IngredientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = RecipeIngredient
        exclude = ('recipe',)


IngredientFormset = forms.modelformset_factory(RecipeIngredient, form=IngredientForm, extra=1)


class AddRecipe(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Recipe
        exclude = ('author',)

book/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, View, ListView, DetailView
from django.urls import reverse_lazy

from book.models import Author, Recipe, RecipeIngredient, Ingredient
from .forms import UserLoginForm, UserRegistrationForm, AddRecipe, IngredientFormset
from django.db.models import Count
from django.db.models import Prefetch


class LoginUserView(LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm


class RegistrationView(CreateView):
    model = Author
    form_class = UserRegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('login')


class PaginatedFilterViews(View):
    def get_context_data(self, **kwargs):
        context = super(PaginatedFilterViews, self).get_context_data(**kwargs)
        if self.request.GET:
            querystring = self.request.GET.copy()
            if self.request.GET.get('page'):
                del querystring['page']
            context['querystring'] = querystring.urlencode()
        return context


class RecipeList(PaginatedFilterViews, ListView):
    model = Recipe
    template_name = 'index.html'
    paginate_by = 3

    def get_queryset(self, **kwargs):
        recipe_ingredient = Prefetch('recipe_ingredient', RecipeIngredient.objects.prefetch_related('ingredient'))
        title = self.request.GET.get('title')
        if title:
            return Recipe.objects.prefetch_related(recipe_ingredient).filter(title__istartswith=title)
        ingredients = self.request.GET.getlist('check')

        if ingredients:

            recipes = RecipeIngredient.objects.filter(ingredient__in=ingredients).values('recipe').annotate(
                cnt=Count('id')).filter(cnt__gt=len(ingredients) - 1).values('recipe')

            return Recipe.objects.prefetch_related(recipe_ingredient).filter(pk__in=recipes)

        elif 'id_author' in self.kwargs:

            return Recipe.objects.prefetch_related(recipe_ingredient).filter(author=self.kwargs['id_author'])
        else:

            return Recipe.objects.prefetch_related(recipe_ingredient).all()


class RecipeDetail(DetailView):
    model = Recipe
    template_name = 'recipe.html'

    def get_object(self, queryset=None):
        recipe_ingredient = Prefetch('recipe_ingredient', RecipeIngredient.objects.prefetch_related('ingredient'))
        return Recipe.objects.select_related().prefetch_related(recipe_ingredient).get(id=self.kwargs['pk'])


class RecipeCreate(CreateView):
    model = Recipe
    form_class = AddRecipe
    template_name = 'add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = IngredientFormset(queryset=RecipeIngredient.objects.none())
        return context

    def post(self, request):
        formset = IngredientFormset(data=self.request.POST)
        form = self.form_class(request.POST, request.FILES)

        if formset.is_valid() and form.is_valid():
            return self.form_valid(formset, form)
        return render(request, self.template_name, {'form': form, 'formset': formset})

    def form_valid(self, formset, form):

        form.instance.author = self.request.user
        form.save()

        instances = formset.save(commit=False)

        for instance in instances:
            instance.recipe = form.save()
            instance.save()

        return HttpResponseRedirect('/')

book/templates/add.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
          <div class="row">
            <div class="col-12">
             
                <form action="{% url 'recipe_create' %}" method="post" enctype="multipart/form-data" id="form-container">
                    {% csrf_token %}
                <h2 class="h2">Новый рецепт</h2>
                <div class="col-12 mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Название</label>
                    {{ form.title }}
                </div>
                <div class="col-12 mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Описание</label>
                   {{ form.description}}
                </div>
                <div class="col-12 mb-3">
                    <label for="formFile" class="form-label">Изображение</label>
                    {{ form.img_recipe }}
                </div>

                <div class="col-12 mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Текст рецепта</label>
                   {{ form.text_recipe}}
                </div>

                {{ formset.management_form }}
                {% for form_set in formset %}
              
               <div class = "ingredient" >
             
                <div class="row g-3">
                <div class="col-6 mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Ингредиенты</label>
                    {{form_set.ingredient}}
                
                </div>

                <div class="col-2 mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Количество</label>
                    {{form_set.quantity}}
                </div>

                <div class="col-3 mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Eдиницы измерения</label>
                    {{form_set.unity}}
                   
                </div>
                </div>
        </div>
   
            {% endfor %}
       
            <div class="col-12 mb-3" id="add-form">
                    
                        <button type="button" class="btn btn-outline-secondary">Добавить ингредиент в рецепт</button>
                            
            </div>
          
                <div class="col-12 mb-3">
                    <input class="btn btn-primary btn-lg" type="submit" value="Сохранить">
               
                </div>

            </div>

          </div>
        </div>

  
        <script src="{% static 'scripts.js' %}"></script> 
   

{% endblock %}

book/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Delicious recipes</title>
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">

          <a href="{% url 'recipes' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M221.6 148.7C224.7 161.3 224.8 174.5 222.1 187.2C219.3 199.1 213.6 211.9 205.6 222.1C191.1 238.6 173 249.1 151.1 254.1V472C151.1 482.6 147.8 492.8 140.3 500.3C132.8 507.8 122.6 512 111.1 512C101.4 512 91.22 507.8 83.71 500.3C76.21 492.8 71.1 482.6 71.1 472V254.1C50.96 250.1 31.96 238.9 18.3 222.4C10.19 212.2 4.529 200.3 1.755 187.5C-1.019 174.7-.8315 161.5 2.303 148.8L32.51 12.45C33.36 8.598 35.61 5.197 38.82 2.9C42.02 .602 45.97-.4297 49.89 .0026C53.82 .4302 57.46 2.303 60.1 5.259C62.74 8.214 64.18 12.04 64.16 16V160H81.53L98.62 11.91C99.02 8.635 100.6 5.621 103.1 3.434C105.5 1.248 108.7 .0401 111.1 .0401C115.3 .0401 118.5 1.248 120.9 3.434C123.4 5.621 124.1 8.635 125.4 11.91L142.5 160H159.1V16C159.1 12.07 161.4 8.268 163.1 5.317C166.6 2.366 170.2 .474 174.1 .0026C178-.4262 181.1 .619 185.2 2.936C188.4 5.253 190.6 8.677 191.5 12.55L221.6 148.7zM448 472C448 482.6 443.8 492.8 436.3 500.3C428.8 507.8 418.6 512 408 512C397.4 512 387.2 507.8 379.7 500.3C372.2 492.8 368 482.6 368 472V352H351.2C342.8 352 334.4 350.3 326.6 347.1C318.9 343.8 311.8 339.1 305.8 333.1C299.9 327.1 295.2 320 291.1 312.2C288.8 304.4 287.2 296 287.2 287.6L287.1 173.8C288 136.9 299.1 100.8 319.8 70.28C340.5 39.71 369.8 16.05 404.1 2.339C408.1 .401 414.2-.3202 419.4 .2391C424.6 .7982 429.6 2.62 433.9 5.546C438.2 8.472 441.8 12.41 444.2 17.03C446.7 21.64 447.1 26.78 448 32V472z"/></svg>
            <span class="fs-4">Delicious recipes</span>
          </a>
          <div class="text-end">
          {% if user.is_authenticated %}
            
           <span class = "user" >{{ user.username }}</span>
            <a href="{% url 'logout' %}" class="btn btn-outline-primary me-2">Выход</a>
          
  
          {% else %}
     
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Вход</a>
            <a href="{% url 'registration' %}" class="btn btn-primary">Регистрация</a>
         
          {% endif %}
        </div>
        </header>
      </div>
      <div class="container">
{% block content %}
{% endblock content %}

</div>
</body>
</html>

book/templates/index.html
{% extends "base.html" %} 
{% load static %}
{% load tags_ingredients %}
{% block content %}
          <h4>Фильтр по ингридиентам</h4>
            <div class="row">
                <div class="col-12">
                    <div class="wrap-filter">
                        {% get_ingredients as ingredients %}
                        <form id="form" method = "GET">
                       
                        {% for ingredient in ingredients %}
                        <input type="checkbox" class="btn-check" id="{{ ingredient.id }}" name="check"  value="{{ ingredient.id }}" autocomplete="off" >
                        <label class="btn btn-outline-primary" for="{{ ingredient.id }}">{{ingredient.title }}</label>
                        {% endfor %}
                    <br>
                    <input type="submit"  class="btn btn-primary" value="Применить">
                </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h2 class="h2">Рецепты</h2>
                    <div class="row">
                        <div class="col-3">
                    <a href="{% url 'recipe_create' %}" class="btn btn-primary add">Добавить новый рецепт</a>
                        </div>
                        <div class="col-9">
                    <form class="col-12 col-lg-4 mb-3 mb-lg-0 me-lg-3"  method="get">
                        <input class="form-control" placeholder="Поиск..." type="text" name="title" onchange="this.form.submit()">

                      </form>
                      <br>
                    </div>
                    </div>
                </div>
            </div>
           
            <div class="wrap">
              
            <div class="row">

                {% for recipe in recipe_list %}
                <div class="col-3">
                    <img src="{{ recipe.img_recipe.url }}" class="rounded img-fluid" alt="...">
                </div>
                <div class="col-9">
                    <h3><a href="{% url 'recipe' recipe.pk %}">{{ recipe.title  }}</a></h3>
                    <div class="wrap-description">
                        {% for ingredient in recipe.recipe_ingredient.all %}
                        <div class="badge bg-secondary" >{{ ingredient.ingredient }}</div>
                        {% endfor %}
                        <p>{{ recipe.description }}</p>
                    
                    </div>
                   </div>
                   {% endfor %}
            </div>
            </div>

                    <div class="pagination-main">
                        <div class="row">
                            <div class="col-12">

                                <nav aria-label="Page navigation example">
                                    <ul class="pagination">

                                        {% if page_obj.has_previous %}
                                      <li class="page-item">
                                        <a class="page-link" href= href="?page={{ page_obj.previous_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Previous">
                                          <span aria-hidden="true">&laquo;</span>
                                        </a>
                                      </li>
                                      {% endif %}
                                      {% for num in page_obj.paginator.page_range %}
                                      {% if num == page_obj.number %}
                                      <li class="page-item">  <a href="?page={{ num }}{% if querystring %}&amp;{{ querystring }}{% endif %} " class="page-link"> {{ num }} </a></li>
                                  {% else %}
                                  <li class="page-item">   <a href="?page={{ num }}{% if querystring %}&amp;{{ querystring }}{% endif %} " class="page-link">{{ num }} </a></li>
                                     {% endif%}

                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li class="page-item">	<a class="page-link" aria-label="Next" href="?page={{ page_obj.next_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}"> <span aria-hidden="true">&raquo;</span></a>
                                     </li>
                                 {% endif%}
                                    </ul>
                                  </nav>

                            </div>
                        </div>

                    </div>

                  
{% endblock %}

book/templates/login.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
    
    <main class="form-signin">
      <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Пожалуйста авторизируйтесь</h1>    
       
        <div class="form-floating">
              {{ form.username }}
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          {{ form.password }}
          <label for="floatingPassword">Пароль</label>
        </div>
    
        <button class="w-100 btn btn-lg btn-primary" type="submit">Вход</button>
        
      </form>
    </main>
    {% endblock %}
    
        
    

book/templates/recipe.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
    <div class="row">

        <div class="wrap">
            <div class="row">
                <div class="col-3">
                    <img src="{{ recipe.img_recipe.url }}" class="rounded img-fluid" alt="...">
                </div>
                <div class="col-9">
                    <h3>{{recipe.title}}</h3>
                    <div class="wrap-description">
                        Автор: <a href="{% url 'author' recipe.author.id %}" class="btn btn-outline-secondary btn-sm">{{recipe.author }}</a>
                        <p>{{ recipe.description }}</p>
                    
                    </div>
                   </div>
                
            </div>
            <div class="row">
                <div class="col-12">
                    <h4 class="h4">Ингредиенты</h4>
                    <ul class="list-group list-group-flush">
                        {% for ingredient in recipe.recipe_ingredient.all %}
                        <li class="list-group-item">{{ ingredient.ingredient }} - {{ ingredient.quantity }} {{ingredient.unity}}</li>
                        {% endfor %}
                      </ul>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <h4 class="h4">Рецепт</h4>
                    <p>{{recipe.text_recipe}}</p>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

book/templates/registration.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
<main class="form-reg">
    <form action="{% url 'registration' %}" method="post" >
        {% csrf_token %}
        <div class="text-center">
            <h4 class="h4 mb-3 fw-normal">Регистрация</h4>
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Ваше имя</label>
            {{ form.username }}
          </div>

          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Ваш e-mail</label>
            {{ form.email }}

          </div>

          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Пароль</label>
            {{ form.password1 }}
          </div>
  

    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Подтверждение пароля</label>
        {{ form.password2 }}
    </div>

    

               <input class="w-100 btn btn-lg btn-primary" type="submit" value="Регистрация">


                {% if form.errors %}
                {{ form.errors }}
                {% endif %}
            </form>
        </main>
        {% endblock %}
        